# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0377093b53a09066c1714396ffa749c8317025da5bfd95aceb43a85586a242bc0a81d9ae49b85fa95b1aca27fab0a37f61412a97d978f119592f285fdcb71788

test:
  secret_key_base: 71853d2eda6f2627657de29bd28c303e82dfc2eed54a47f112329d9e54809760c98b97f51b523eba5ff94e7a770013cfa6c81190032efcc267dcaca4b74cd930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
